services:
  - type: web
    name: fra-atlas-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: MAX_FILE_SIZE
        value: 50mb
      - key: TENSORFLOW_BACKEND
        value: cpu
      - key: OCR_CONFIDENCE_THRESHOLD
        value: 0.8
